version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: novadocs-postgres
    environment:
      POSTGRES_DB: novadocs
      POSTGRES_USER: novadocs
      POSTGRES_PASSWORD: novadocs
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novadocs -d novadocs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
